### ISSUE TITLE
Progress bar is not working

### ISSUE THREAD

**Issue by wenlongren** [broadinstitute/colab-repeat-finder#3]
Thank the developers for creating the program to find perfect repeats; it has been very helpful for our research. During use, we noticed that the progress bar isn't functioning, which could be misleading and give the impression that the software isn't working, when in fact it is running fine.

![Screenshot](https://github.com/user-attachments/assets/1b307fda-3de8-40e8-9010-e27457578c72)

**Comment by bw2** [comment]
Thanks for reporting the issue. It should be fixed now.
